### PR TITLE
Modifications to MANIFEST, SConstruct for easier macOS compilation

### PR DESCRIPTION
**Pull request by evanheller**
For compilation on macOS, MANIFEST.in needs to include .dylib files so that they're copied to the installation directory. Libraries like fftw3 are usually installed to /usr/local; setting CCFLAGS and fftw_lib_path to point here are helpful to make the install script work without having to export these and run SCons manually.

### CODE REVIEW

**Comment by HazenBabcock** [comment]
Are you planning to resolve the SConstruct merge conflict? Or do you want me to?

**Comment by HazenBabcock** [comment]
Also, are the CCFLAGS and LDFLAGS that you want to add typically in the users current environment? I realized when I was trying to compile this project on the RC cluster that what I wanted to use was:
`env = Environment(ENV = os.environ)`
and not:
`env = DefaultEnvironment()`
in order to compile in the users current environment instead of the default (mostly empty?) environment. Right now this change is still in a private branch, but if it solves this issue then we could just fix that line.

I'm a little leery of the approach of using fixed paths as you propose because that might not be the location of the fftw3 library that the user actually wants to use.

**Comment by evanheller** [comment]
As far as I can tell, these variables are not typically in the environment. The C compiler that comes with Xcode on Macs for some reason does not search /usr/local (unlike gcc), whereas anything a user might install from source or a package manager like Homebrew usually ends up there. It’s true, it may not be the right fftw3, but the user wants to use a version that’s not in a “normal” location, they’d have to intervene manually anyway.

**Comment by HazenBabcock** [comment]
Okay, merged, thanks!

However, we may be overwriting the values for CCFLAGS and LDFLAGS that the user provides, so manual intervention could involve modifying the SConstruct file instead of simply exporting these environment variables? I guess we'll see if we get any complaints..

**Pull request merged**
